export {
  SETTINGS_CATALOG_DEFAULT_JS,
  SETTINGS_CATALOG_DEFAULT_JSON,
  SETTINGS_CATALOG_FORMAT,
  SETTINGS_CATALOG_INPUT_IDS,
  SETTINGS_CATALOG_TEXTAREA_ROWS,
} from '@pages/Cms/SettingsPages/SettingsPages.const';
