export type ContentRowActionsProps = {
  id: string;
  status: string;
  catalog?: boolean;
  openLabel: string;
  moreLabel: string;
  editLabel: string;
  stageLabel: string;
  duplicateLabel: string;
  homepageLabel: string;
  draftLabel: string;
  publishLabel: string;
  deleteLabel: string;
  deleteTitle: string;
  deleteBody: string;
  deleteConfirm: string;
  deleteCancel: string;
  deleting: boolean;
  onOpen: (id: string) => void;
  onStage: (id: string) => void;
  onDuplicate: (id: string) => void;
  onHomepage: (id: string) => void;
  onDraft: (id: string) => void;
  onPublish: (id: string) => void;
  onDelete: (id: string) => void;
};
