export const ROUTES = {
  HOME: '/',
  DOCS: '/docs',
  DOC_PAGE: '/docs/:slug',
  DOCS_SLUG: '/docs/:slug',
  GUIDES: '/docs/how-to-use',
  API: '/api',
  DEMOS: '/demos',
  DEMO_FEATURE: '/demos/feature-rich',
  DEMO_AI: '/demos/ai',
  DEMO_COLLAB: '/demos/collaborative',
  DEMO_DOCUMENT: '/demos/document',
  DEMO_TABLES: '/demos/tables',
  DEMO_MARKDOWN: '/demos/markdown',
  DEMO_MOBILE: '/demos/mobile',
  PLAYGROUND: '/playground',
  GET_STARTED: '/get-started',
  CHANGELOG: '/changelog',
  STATUS: '/status',
  AI: '/ai',
  ASK_AI: '/ai',
  PRICING: '/pricing',
  PLANS: '/plans',
  DEMO: '/demo',
  MCP: '/docs/mcp',
  PREMIUM_SUCCESS: '/pricing/success',
  TERMS: '/terms',
  LOGIN: '/cms/login',
  LOGIN_PUBLIC: '/login',
  CMS: '/cms',
  CMS_LOGIN: '/cms/login',
  CMS_CONTENT: '/cms/content',
  CMS_EDIT: '/cms/edit/:id',
  CMS_MEDIA: '/cms/media',
  CMS_EDITORS: '/cms/editors',
  CMS_CREW: '/cms/crew',
  CMS_LIVE_EDIT: '/cms/live-edit',
  CMS_EXTENSIONS: '/cms/extensions',
  CMS_PLANS: '/cms/plans',
  CMS_CALENDAR: '/cms/calendar',
  CMS_SETTINGS: '/cms/settings',
  CMS_DEVELOPER: '/cms/developer',
  CMS_AUDIT: '/cms/audit',
  CMS_NOTIFICATIONS: '/cms/notifications',
  CMS_TEMPLATES: '/cms/templates',
  CMS_BUILDER: '/cms/builder',
  CMS_TRANSLATIONS: '/cms/translations',
  CMS_CAST: '/cms/cast',
  CMS_TASKS: '/cms/tasks',
  CMS_BLOG: '/cms/blog',
  CMS_BLOG_EDIT: '/cms/blog/:id',
  BLOG: '/blog',
  BLOG_POST: '/blog/:slug',
  SENSORS: '/sensors',
  PAGES: '/pages',
  NOT_FOUND: '/404',
  LAB: '/lab',
} as const;

export const BUILDER_QUERY_DOC = 'doc';
export const BUILDER_QUERY_LAYOUT = 'layout';

export const PUBLIC_NAV_IDS = {
  PRODUCT: 'product',
  DOCS: 'docs',
  PLANS: 'plans',
  DEMO: 'demo',
  CHANGELOG: 'changelog',
  STATUS: 'status',
  BLOG: 'blog',
  GUIDES: 'guides',
  API: 'api',
  ASK_AI: 'askAi',
} as const;

export const SHOW_LAB_NAV = false;

export const NAV_LINKS_BASE = [
  { id: PUBLIC_NAV_IDS.DOCS, href: ROUTES.DOCS },
  { id: 'demos' as const, href: ROUTES.DEMOS },
  { id: 'pricing' as const, href: ROUTES.PRICING },
  { id: 'plugins' as const, href: `${ROUTES.DOCS}/plugins` },
];

export const DEFAULT_DOC_SLUG = 'overview';
export const DOC_INSTALLATION_SLUG = 'installation';
