import { NUMBER_EIGHT_HUNDRED } from '@const/numbers.const';
import {
  HERO_IMG_SRC,
  HTML_TAG_DIV,
  HTML_TAG_IMG,
} from '@const/strings.const';
import { bearWidgetHtml } from '../ContentEdit/bearWidget.utils';
import type { BearPaletteWidget } from './BearPalette.types';

export const BEAR_PALETTE_GROUP = {
  BASIC: 'basic',
  LAYOUT: 'layout',
  FORM: 'form',
  MEDIA: 'media',
  FEEDBACK: 'feedback',
  OVERLAY: 'overlay',
  GENERAL: 'general',
} as const;

export const BEAR_IMAGE_WIDGET_ID = 'image';
export const IMAGE_ATTR_SRC = 'src';
export const IMAGE_ATTR_ALT = 'alt';
export const IMAGE_ATTR_WIDTH = 'width';
export const IMAGE_ATTR_HEIGHT = 'height';
export const IMAGE_ATTR_LOADING = 'loading';
export const IMAGE_LOADING_LAZY = 'lazy';
export const BEAR_IMAGE_ALT = 'Image';
export const IMAGE_OPEN_TAG = `<${HTML_TAG_IMG}`;

export const BEAR_IMAGE_HTML = `<${HTML_TAG_IMG} src="${HERO_IMG_SRC}" alt="${BEAR_IMAGE_ALT}" width="${NUMBER_EIGHT_HUNDRED}" loading="${IMAGE_LOADING_LAZY}" />`;

export const IMAGE_ATTR_KEYS = [
  IMAGE_ATTR_SRC,
  IMAGE_ATTR_ALT,
  IMAGE_ATTR_WIDTH,
  IMAGE_ATTR_HEIGHT,
  IMAGE_ATTR_LOADING,
] as const;

export type ImageAttrKey = (typeof IMAGE_ATTR_KEYS)[number];

export const IMAGE_ATTR_BY_FIELD = {
  src: IMAGE_ATTR_SRC,
  alt: IMAGE_ATTR_ALT,
  width: IMAGE_ATTR_WIDTH,
  height: IMAGE_ATTR_HEIGHT,
  loading: IMAGE_ATTR_LOADING,
} as const;

const wrap = (component: string, inner: string): string =>
  bearWidgetHtml(component, inner, HTML_TAG_DIV);

export const BEAR_PALETTE: readonly BearPaletteWidget[] = [
  {
    id: 'accordion',
    label: 'Accordion',
    bearComponent: 'Accordion',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Accordion', 'Accordion'),
  },
  {
    id: 'action-icon',
    label: 'ActionIcon',
    bearComponent: 'ActionIcon',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('ActionIcon', 'ActionIcon'),
  },
  {
    id: 'active-bar',
    label: 'ActiveBar',
    bearComponent: 'ActiveBar',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('ActiveBar', 'ActiveBar'),
  },
  {
    id: 'activity-item',
    label: 'ActivityItem',
    bearComponent: 'ActivityItem',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('ActivityItem', 'ActivityItem'),
  },
  {
    id: 'affix',
    label: 'Affix',
    bearComponent: 'Affix',
    group: BEAR_PALETTE_GROUP.LAYOUT,
    html: wrap('Affix', 'Affix'),
  },
  {
    id: 'alert',
    label: 'Alert',
    bearComponent: 'Alert',
    group: BEAR_PALETTE_GROUP.FEEDBACK,
    html: wrap('Alert', '<strong>Alert</strong><p>Important notice.</p>'),
  },
  {
    id: 'alert-dialog',
    label: 'AlertDialog',
    bearComponent: 'AlertDialog',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('AlertDialog', 'AlertDialog'),
  },
  {
    id: 'anchor',
    label: 'Anchor',
    bearComponent: 'Anchor',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Anchor', 'Anchor'),
  },
  {
    id: 'animated-counter',
    label: 'AnimatedCounter',
    bearComponent: 'AnimatedCounter',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('AnimatedCounter', 'AnimatedCounter'),
  },
  {
    id: 'app-bar',
    label: 'AppBar',
    bearComponent: 'AppBar',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('AppBar', 'AppBar'),
  },
  {
    id: 'app-shell',
    label: 'AppShell',
    bearComponent: 'AppShell',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('AppShell', 'AppShell'),
  },
  {
    id: 'aspect-ratio',
    label: 'AspectRatio',
    bearComponent: 'AspectRatio',
    group: BEAR_PALETTE_GROUP.LAYOUT,
    html: wrap('AspectRatio', 'AspectRatio'),
  },
  {
    id: 'autocomplete',
    label: 'Autocomplete',
    bearComponent: 'Autocomplete',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('Autocomplete', 'Autocomplete'),
  },
  {
    id: 'avatar',
    label: 'Avatar',
    bearComponent: 'Avatar',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Avatar', 'Avatar'),
  },
  {
    id: 'back-top',
    label: 'BackTop',
    bearComponent: 'BackTop',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('BackTop', 'BackTop'),
  },
  {
    id: 'backdrop',
    label: 'Backdrop',
    bearComponent: 'Backdrop',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Backdrop', 'Backdrop'),
  },
  {
    id: 'badge',
    label: 'Badge',
    bearComponent: 'Badge',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Badge', 'Badge'),
  },
  {
    id: 'banner',
    label: 'Banner',
    bearComponent: 'Banner',
    group: BEAR_PALETTE_GROUP.FEEDBACK,
    html: wrap('Banner', 'Banner'),
  },
  {
    id: 'bear-loader',
    label: 'BearLoader',
    bearComponent: 'BearLoader',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('BearLoader', 'BearLoader'),
  },
  {
    id: 'bear-logo',
    label: 'BearLogo',
    bearComponent: 'BearLogo',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('BearLogo', 'BearLogo'),
  },
  {
    id: 'biometric',
    label: 'Biometric',
    bearComponent: 'Biometric',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Biometric', 'Biometric'),
  },
  {
    id: 'blockquote',
    label: 'Blockquote',
    bearComponent: 'Blockquote',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Blockquote', 'Blockquote'),
  },
  {
    id: 'bottom-navigation',
    label: 'BottomNavigation',
    bearComponent: 'BottomNavigation',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('BottomNavigation', 'BottomNavigation'),
  },
  {
    id: 'bottom-sheet',
    label: 'BottomSheet',
    bearComponent: 'BottomSheet',
    group: BEAR_PALETTE_GROUP.OVERLAY,
    html: wrap('BottomSheet', 'BottomSheet'),
  },
  {
    id: 'box',
    label: 'Box',
    bearComponent: 'Box',
    group: BEAR_PALETTE_GROUP.LAYOUT,
    html: wrap('Box', 'Box'),
  },
  {
    id: 'breadcrumbs',
    label: 'Breadcrumbs',
    bearComponent: 'Breadcrumbs',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Breadcrumbs', 'Breadcrumbs'),
  },
  {
    id: 'button',
    label: 'Button',
    bearComponent: 'Button',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Button', '<a href="#">Button</a>'),
  },
  {
    id: 'button-group',
    label: 'ButtonGroup',
    bearComponent: 'ButtonGroup',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('ButtonGroup', 'ButtonGroup'),
  },
  {
    id: 'calendar',
    label: 'Calendar',
    bearComponent: 'Calendar',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Calendar', 'Calendar'),
  },
  {
    id: 'card',
    label: 'Card',
    bearComponent: 'Card',
    group: BEAR_PALETTE_GROUP.LAYOUT,
    html: wrap('Card', '<p><strong>Card</strong></p><p>Card body content.</p>'),
  },
  {
    id: 'card-skeleton',
    label: 'CardSkeleton',
    bearComponent: 'CardSkeleton',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('CardSkeleton', 'CardSkeleton'),
  },
  {
    id: 'carousel',
    label: 'Carousel',
    bearComponent: 'Carousel',
    group: BEAR_PALETTE_GROUP.MEDIA,
    html: wrap('Carousel', 'Carousel'),
  },
  {
    id: 'cascader',
    label: 'Cascader',
    bearComponent: 'Cascader',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('Cascader', 'Cascader'),
  },
  {
    id: 'chart',
    label: 'Chart',
    bearComponent: 'Chart',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Chart', 'Chart'),
  },
  {
    id: 'chat',
    label: 'Chat',
    bearComponent: 'Chat',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Chat', 'Chat'),
  },
  {
    id: 'checkbox',
    label: 'Checkbox',
    bearComponent: 'Checkbox',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('Checkbox', 'Checkbox'),
  },
  {
    id: 'checkbox-card',
    label: 'CheckboxCard',
    bearComponent: 'CheckboxCard',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('CheckboxCard', 'CheckboxCard'),
  },
  {
    id: 'chip',
    label: 'Chip',
    bearComponent: 'Chip',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Chip', 'Chip'),
  },
  {
    id: 'chip-group',
    label: 'ChipGroup',
    bearComponent: 'ChipGroup',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('ChipGroup', 'ChipGroup'),
  },
  {
    id: 'close-button',
    label: 'CloseButton',
    bearComponent: 'CloseButton',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('CloseButton', 'CloseButton'),
  },
  {
    id: 'code-block',
    label: 'CodeBlock',
    bearComponent: 'CodeBlock',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('CodeBlock', 'CodeBlock'),
  },
  {
    id: 'code-editor',
    label: 'CodeEditor',
    bearComponent: 'CodeEditor',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('CodeEditor', 'CodeEditor'),
  },
  {
    id: 'collapsible',
    label: 'Collapsible',
    bearComponent: 'Collapsible',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Collapsible', 'Collapsible'),
  },
  {
    id: 'color-picker',
    label: 'ColorPicker',
    bearComponent: 'ColorPicker',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('ColorPicker', 'ColorPicker'),
  },
  {
    id: 'color-swatch',
    label: 'ColorSwatch',
    bearComponent: 'ColorSwatch',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('ColorSwatch', 'ColorSwatch'),
  },
  {
    id: 'columns',
    label: 'Columns',
    bearComponent: 'Columns',
    group: BEAR_PALETTE_GROUP.LAYOUT,
    html: wrap('Columns', 'Columns'),
  },
  {
    id: 'command-palette',
    label: 'CommandPalette',
    bearComponent: 'CommandPalette',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('CommandPalette', 'CommandPalette'),
  },
  {
    id: 'confetti',
    label: 'Confetti',
    bearComponent: 'Confetti',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Confetti', 'Confetti'),
  },
  {
    id: 'container',
    label: 'Container',
    bearComponent: 'Container',
    group: BEAR_PALETTE_GROUP.LAYOUT,
    html: wrap('Container', 'Container'),
  },
  {
    id: 'context-menu',
    label: 'ContextMenu',
    bearComponent: 'ContextMenu',
    group: BEAR_PALETTE_GROUP.OVERLAY,
    html: wrap('ContextMenu', 'ContextMenu'),
  },
  {
    id: 'copy-button',
    label: 'CopyButton',
    bearComponent: 'CopyButton',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('CopyButton', 'CopyButton'),
  },
  {
    id: 'countdown-timer',
    label: 'CountdownTimer',
    bearComponent: 'CountdownTimer',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('CountdownTimer', 'CountdownTimer'),
  },
  {
    id: 'credit-input',
    label: 'CreditInput',
    bearComponent: 'CreditInput',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('CreditInput', 'CreditInput'),
  },
  {
    id: 'cropper',
    label: 'Cropper',
    bearComponent: 'Cropper',
    group: BEAR_PALETTE_GROUP.MEDIA,
    html: wrap('Cropper', 'Cropper'),
  },
  {
    id: 'currency-input',
    label: 'CurrencyInput',
    bearComponent: 'CurrencyInput',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('CurrencyInput', 'CurrencyInput'),
  },
  {
    id: 'data-table',
    label: 'DataTable',
    bearComponent: 'DataTable',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('DataTable', 'DataTable'),
  },
  {
    id: 'date-picker',
    label: 'DatePicker',
    bearComponent: 'DatePicker',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('DatePicker', 'DatePicker'),
  },
  {
    id: 'date-range-picker',
    label: 'DateRangePicker',
    bearComponent: 'DateRangePicker',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('DateRangePicker', 'DateRangePicker'),
  },
  {
    id: 'descriptions',
    label: 'Descriptions',
    bearComponent: 'Descriptions',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Descriptions', 'Descriptions'),
  },
  {
    id: 'diff-squares',
    label: 'DiffSquares',
    bearComponent: 'DiffSquares',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('DiffSquares', 'DiffSquares'),
  },
  {
    id: 'diff-viewer',
    label: 'DiffViewer',
    bearComponent: 'DiffViewer',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('DiffViewer', 'DiffViewer'),
  },
  {
    id: 'divider',
    label: 'Divider',
    bearComponent: 'Divider',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Divider', 'Divider'),
  },
  {
    id: 'dock',
    label: 'Dock',
    bearComponent: 'Dock',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Dock', 'Dock'),
  },
  {
    id: 'drawer',
    label: 'Drawer',
    bearComponent: 'Drawer',
    group: BEAR_PALETTE_GROUP.OVERLAY,
    html: wrap('Drawer', 'Drawer'),
  },
  {
    id: 'dropdown',
    label: 'Dropdown',
    bearComponent: 'Dropdown',
    group: BEAR_PALETTE_GROUP.OVERLAY,
    html: wrap('Dropdown', 'Dropdown'),
  },
  {
    id: 'editable',
    label: 'Editable',
    bearComponent: 'Editable',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Editable', 'Editable'),
  },
  {
    id: 'em',
    label: 'Em',
    bearComponent: 'Em',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Em', 'Em'),
  },
  {
    id: 'emoji-picker',
    label: 'EmojiPicker',
    bearComponent: 'EmojiPicker',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('EmojiPicker', 'EmojiPicker'),
  },
  {
    id: 'empty-state',
    label: 'EmptyState',
    bearComponent: 'EmptyState',
    group: BEAR_PALETTE_GROUP.FEEDBACK,
    html: wrap('EmptyState', 'EmptyState'),
  },
  {
    id: 'fab',
    label: 'Fab',
    bearComponent: 'Fab',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Fab', 'Fab'),
  },
  {
    id: 'fieldset',
    label: 'Fieldset',
    bearComponent: 'Fieldset',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Fieldset', 'Fieldset'),
  },
  {
    id: 'file-tree',
    label: 'FileTree',
    bearComponent: 'FileTree',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('FileTree', 'FileTree'),
  },
  {
    id: 'file-upload',
    label: 'FileUpload',
    bearComponent: 'FileUpload',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('FileUpload', 'FileUpload'),
  },
  {
    id: 'flex',
    label: 'Flex',
    bearComponent: 'Flex',
    group: BEAR_PALETTE_GROUP.LAYOUT,
    html: wrap('Flex', '<p>Flex item A</p><p>Flex item B</p>'),
  },
  {
    id: 'floating-chat',
    label: 'FloatingChat',
    bearComponent: 'FloatingChat',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('FloatingChat', 'FloatingChat'),
  },
  {
    id: 'form',
    label: 'Form',
    bearComponent: 'Form',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('Form', 'Form'),
  },
  {
    id: 'form-control',
    label: 'FormControl',
    bearComponent: 'FormControl',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('FormControl', 'FormControl'),
  },
  {
    id: 'form-field',
    label: 'FormField',
    bearComponent: 'FormField',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('FormField', 'FormField'),
  },
  {
    id: 'form-skeleton',
    label: 'FormSkeleton',
    bearComponent: 'FormSkeleton',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('FormSkeleton', 'FormSkeleton'),
  },
  {
    id: 'gauge',
    label: 'Gauge',
    bearComponent: 'Gauge',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Gauge', 'Gauge'),
  },
  {
    id: 'glow-card',
    label: 'GlowCard',
    bearComponent: 'GlowCard',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('GlowCard', 'GlowCard'),
  },
  {
    id: 'gradient-text',
    label: 'GradientText',
    bearComponent: 'GradientText',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('GradientText', 'GradientText'),
  },
  {
    id: 'grid',
    label: 'Grid',
    bearComponent: 'Grid',
    group: BEAR_PALETTE_GROUP.LAYOUT,
    html: wrap('Grid', '<p>Grid A</p><p>Grid B</p><p>Grid C</p>'),
  },
  {
    id: 'heatmap',
    label: 'Heatmap',
    bearComponent: 'Heatmap',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Heatmap', 'Heatmap'),
  },
  {
    id: 'highlight',
    label: 'Highlight',
    bearComponent: 'Highlight',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Highlight', 'Highlight'),
  },
  {
    id: 'hover-card',
    label: 'HoverCard',
    bearComponent: 'HoverCard',
    group: BEAR_PALETTE_GROUP.OVERLAY,
    html: wrap('HoverCard', 'HoverCard'),
  },
  {
    id: 'icon',
    label: 'Icon',
    bearComponent: 'Icon',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Icon', 'Icon'),
  },
  {
    id: 'image',
    label: 'Image',
    bearComponent: 'Image',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: BEAR_IMAGE_HTML,
  },
  {
    id: 'image-annotation',
    label: 'ImageAnnotation',
    bearComponent: 'ImageAnnotation',
    group: BEAR_PALETTE_GROUP.MEDIA,
    html: wrap('ImageAnnotation', 'ImageAnnotation'),
  },
  {
    id: 'image-gallery',
    label: 'ImageGallery',
    bearComponent: 'ImageGallery',
    group: BEAR_PALETTE_GROUP.MEDIA,
    html: wrap('ImageGallery', 'ImageGallery'),
  },
  {
    id: 'indicator',
    label: 'Indicator',
    bearComponent: 'Indicator',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Indicator', 'Indicator'),
  },
  {
    id: 'infinite-scroll',
    label: 'InfiniteScroll',
    bearComponent: 'InfiniteScroll',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('InfiniteScroll', 'InfiniteScroll'),
  },
  {
    id: 'input',
    label: 'Input',
    bearComponent: 'Input',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('Input', '<input type="text" placeholder="Input" />'),
  },
  {
    id: 'input-group',
    label: 'InputGroup',
    bearComponent: 'InputGroup',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('InputGroup', 'InputGroup'),
  },
  {
    id: 'json-viewer',
    label: 'JsonViewer',
    bearComponent: 'JsonViewer',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('JsonViewer', 'JsonViewer'),
  },
  {
    id: 'kanban',
    label: 'Kanban',
    bearComponent: 'Kanban',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Kanban', 'Kanban'),
  },
  {
    id: 'kbd',
    label: 'Kbd',
    bearComponent: 'Kbd',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Kbd', 'Kbd'),
  },
  {
    id: 'link',
    label: 'Link',
    bearComponent: 'Link',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Link', 'Link'),
  },
  {
    id: 'list',
    label: 'List',
    bearComponent: 'List',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('List', 'List'),
  },
  {
    id: 'loading-overlay',
    label: 'LoadingOverlay',
    bearComponent: 'LoadingOverlay',
    group: BEAR_PALETTE_GROUP.FEEDBACK,
    html: wrap('LoadingOverlay', 'LoadingOverlay'),
  },
  {
    id: 'map',
    label: 'Map',
    bearComponent: 'Map',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Map', 'Map'),
  },
  {
    id: 'mark',
    label: 'Mark',
    bearComponent: 'Mark',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Mark', 'Mark'),
  },
  {
    id: 'marquee',
    label: 'Marquee',
    bearComponent: 'Marquee',
    group: BEAR_PALETTE_GROUP.MEDIA,
    html: wrap('Marquee', 'Marquee'),
  },
  {
    id: 'masonry',
    label: 'Masonry',
    bearComponent: 'Masonry',
    group: BEAR_PALETTE_GROUP.LAYOUT,
    html: wrap('Masonry', 'Masonry'),
  },
  {
    id: 'media-player',
    label: 'MediaPlayer',
    bearComponent: 'MediaPlayer',
    group: BEAR_PALETTE_GROUP.MEDIA,
    html: wrap('MediaPlayer', 'MediaPlayer'),
  },
  {
    id: 'mentions-input',
    label: 'MentionsInput',
    bearComponent: 'MentionsInput',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('MentionsInput', 'MentionsInput'),
  },
  {
    id: 'menu',
    label: 'Menu',
    bearComponent: 'Menu',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Menu', 'Menu'),
  },
  {
    id: 'message-list',
    label: 'MessageList',
    bearComponent: 'MessageList',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('MessageList', 'MessageList'),
  },
  {
    id: 'modal',
    label: 'Modal',
    bearComponent: 'Modal',
    group: BEAR_PALETTE_GROUP.OVERLAY,
    html: wrap('Modal', 'Modal'),
  },
  {
    id: 'multi-select',
    label: 'MultiSelect',
    bearComponent: 'MultiSelect',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('MultiSelect', 'MultiSelect'),
  },
  {
    id: 'navigable-select',
    label: 'NavigableSelect',
    bearComponent: 'NavigableSelect',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('NavigableSelect', 'NavigableSelect'),
  },
  {
    id: 'notification-center',
    label: 'NotificationCenter',
    bearComponent: 'NotificationCenter',
    group: BEAR_PALETTE_GROUP.FEEDBACK,
    html: wrap('NotificationCenter', 'NotificationCenter'),
  },
  {
    id: 'number-formatter',
    label: 'NumberFormatter',
    bearComponent: 'NumberFormatter',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('NumberFormatter', 'NumberFormatter'),
  },
  {
    id: 'number-input',
    label: 'NumberInput',
    bearComponent: 'NumberInput',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('NumberInput', 'NumberInput'),
  },
  {
    id: 'otpinput',
    label: 'OTPInput',
    bearComponent: 'OTPInput',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('OTPInput', 'OTPInput'),
  },
  {
    id: 'overlay',
    label: 'Overlay',
    bearComponent: 'Overlay',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Overlay', 'Overlay'),
  },
  {
    id: 'page-header',
    label: 'PageHeader',
    bearComponent: 'PageHeader',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('PageHeader', 'PageHeader'),
  },
  {
    id: 'page-nav',
    label: 'PageNav',
    bearComponent: 'PageNav',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('PageNav', 'PageNav'),
  },
  {
    id: 'pagination',
    label: 'Pagination',
    bearComponent: 'Pagination',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Pagination', 'Pagination'),
  },
  {
    id: 'paper',
    label: 'Paper',
    bearComponent: 'Paper',
    group: BEAR_PALETTE_GROUP.LAYOUT,
    html: wrap('Paper', 'Paper'),
  },
  {
    id: 'password-input',
    label: 'PasswordInput',
    bearComponent: 'PasswordInput',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('PasswordInput', 'PasswordInput'),
  },
  {
    id: 'phone-input',
    label: 'PhoneInput',
    bearComponent: 'PhoneInput',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('PhoneInput', 'PhoneInput'),
  },
  {
    id: 'popconfirm',
    label: 'Popconfirm',
    bearComponent: 'Popconfirm',
    group: BEAR_PALETTE_GROUP.OVERLAY,
    html: wrap('Popconfirm', 'Popconfirm'),
  },
  {
    id: 'popover',
    label: 'Popover',
    bearComponent: 'Popover',
    group: BEAR_PALETTE_GROUP.OVERLAY,
    html: wrap('Popover', 'Popover'),
  },
  {
    id: 'progress',
    label: 'Progress',
    bearComponent: 'Progress',
    group: BEAR_PALETTE_GROUP.FEEDBACK,
    html: wrap('Progress', 'Progress'),
  },
  {
    id: 'qrcode',
    label: 'QRCode',
    bearComponent: 'QRCode',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('QRCode', 'QRCode'),
  },
  {
    id: 'radio',
    label: 'Radio',
    bearComponent: 'Radio',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('Radio', 'Radio'),
  },
  {
    id: 'radio-card',
    label: 'RadioCard',
    bearComponent: 'RadioCard',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('RadioCard', 'RadioCard'),
  },
  {
    id: 'rating',
    label: 'Rating',
    bearComponent: 'Rating',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Rating', 'Rating'),
  },
  {
    id: 'resizable-panel',
    label: 'ResizablePanel',
    bearComponent: 'ResizablePanel',
    group: BEAR_PALETTE_GROUP.LAYOUT,
    html: wrap('ResizablePanel', 'ResizablePanel'),
  },
  {
    id: 'resizable-textarea',
    label: 'ResizableTextarea',
    bearComponent: 'ResizableTextarea',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('ResizableTextarea', 'ResizableTextarea'),
  },
  {
    id: 'result',
    label: 'Result',
    bearComponent: 'Result',
    group: BEAR_PALETTE_GROUP.FEEDBACK,
    html: wrap('Result', 'Result'),
  },
  {
    id: 'rich-editor',
    label: 'RichEditor',
    bearComponent: 'RichEditor',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('RichEditor', 'RichEditor'),
  },
  {
    id: 'ring-progress',
    label: 'RingProgress',
    bearComponent: 'RingProgress',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('RingProgress', 'RingProgress'),
  },
  {
    id: 'scroll-area',
    label: 'ScrollArea',
    bearComponent: 'ScrollArea',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('ScrollArea', 'ScrollArea'),
  },
  {
    id: 'segmented-control',
    label: 'SegmentedControl',
    bearComponent: 'SegmentedControl',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('SegmentedControl', 'SegmentedControl'),
  },
  {
    id: 'select',
    label: 'Select',
    bearComponent: 'Select',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('Select', 'Select'),
  },
  {
    id: 'sidebar',
    label: 'Sidebar',
    bearComponent: 'Sidebar',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Sidebar', 'Sidebar'),
  },
  {
    id: 'sign-pad',
    label: 'SignPad',
    bearComponent: 'SignPad',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('SignPad', 'SignPad'),
  },
  {
    id: 'skeleton',
    label: 'Skeleton',
    bearComponent: 'Skeleton',
    group: BEAR_PALETTE_GROUP.FEEDBACK,
    html: wrap('Skeleton', 'Skeleton'),
  },
  {
    id: 'slider',
    label: 'Slider',
    bearComponent: 'Slider',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Slider', 'Slider'),
  },
  {
    id: 'slider-range',
    label: 'SliderRange',
    bearComponent: 'SliderRange',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('SliderRange', 'SliderRange'),
  },
  {
    id: 'snackbar',
    label: 'Snackbar',
    bearComponent: 'Snackbar',
    group: BEAR_PALETTE_GROUP.FEEDBACK,
    html: wrap('Snackbar', 'Snackbar'),
  },
  {
    id: 'sparkline',
    label: 'Sparkline',
    bearComponent: 'Sparkline',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Sparkline', 'Sparkline'),
  },
  {
    id: 'speed-dial',
    label: 'SpeedDial',
    bearComponent: 'SpeedDial',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('SpeedDial', 'SpeedDial'),
  },
  {
    id: 'spinner',
    label: 'Spinner',
    bearComponent: 'Spinner',
    group: BEAR_PALETTE_GROUP.FEEDBACK,
    html: wrap('Spinner', 'Spinner'),
  },
  {
    id: 'split-button',
    label: 'SplitButton',
    bearComponent: 'SplitButton',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('SplitButton', 'SplitButton'),
  },
  {
    id: 'spoiler',
    label: 'Spoiler',
    bearComponent: 'Spoiler',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Spoiler', 'Spoiler'),
  },
  {
    id: 'spotlight',
    label: 'Spotlight',
    bearComponent: 'Spotlight',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Spotlight', 'Spotlight'),
  },
  {
    id: 'stat-card',
    label: 'StatCard',
    bearComponent: 'StatCard',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('StatCard', 'StatCard'),
  },
  {
    id: 'statistic',
    label: 'Statistic',
    bearComponent: 'Statistic',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Statistic', 'Statistic'),
  },
  {
    id: 'stepper',
    label: 'Stepper',
    bearComponent: 'Stepper',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Stepper', 'Stepper'),
  },
  {
    id: 'switch',
    label: 'Switch',
    bearComponent: 'Switch',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('Switch', 'Switch'),
  },
  {
    id: 'table-skeleton',
    label: 'TableSkeleton',
    bearComponent: 'TableSkeleton',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('TableSkeleton', 'TableSkeleton'),
  },
  {
    id: 'tabs',
    label: 'Tabs',
    bearComponent: 'Tabs',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Tabs', 'Tabs'),
  },
  {
    id: 'tag-cloud',
    label: 'TagCloud',
    bearComponent: 'TagCloud',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('TagCloud', 'TagCloud'),
  },
  {
    id: 'tags-input',
    label: 'TagsInput',
    bearComponent: 'TagsInput',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('TagsInput', 'TagsInput'),
  },
  {
    id: 'terminal',
    label: 'Terminal',
    bearComponent: 'Terminal',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Terminal', 'Terminal'),
  },
  {
    id: 'theme-icon',
    label: 'ThemeIcon',
    bearComponent: 'ThemeIcon',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('ThemeIcon', 'ThemeIcon'),
  },
  {
    id: 'time-picker',
    label: 'TimePicker',
    bearComponent: 'TimePicker',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('TimePicker', 'TimePicker'),
  },
  {
    id: 'timeline',
    label: 'Timeline',
    bearComponent: 'Timeline',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Timeline', 'Timeline'),
  },
  {
    id: 'timeline-chart',
    label: 'TimelineChart',
    bearComponent: 'TimelineChart',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('TimelineChart', 'TimelineChart'),
  },
  {
    id: 'toast',
    label: 'Toast',
    bearComponent: 'Toast',
    group: BEAR_PALETTE_GROUP.FEEDBACK,
    html: wrap('Toast', 'Toast'),
  },
  {
    id: 'toggle-button',
    label: 'ToggleButton',
    bearComponent: 'ToggleButton',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('ToggleButton', 'ToggleButton'),
  },
  {
    id: 'tooltip',
    label: 'Tooltip',
    bearComponent: 'Tooltip',
    group: BEAR_PALETTE_GROUP.OVERLAY,
    html: wrap('Tooltip', 'Tooltip'),
  },
  {
    id: 'tour',
    label: 'Tour',
    bearComponent: 'Tour',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Tour', 'Tour'),
  },
  {
    id: 'transfer-list',
    label: 'TransferList',
    bearComponent: 'TransferList',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('TransferList', 'TransferList'),
  },
  {
    id: 'transition',
    label: 'Transition',
    bearComponent: 'Transition',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Transition', 'Transition'),
  },
  {
    id: 'tree-select',
    label: 'TreeSelect',
    bearComponent: 'TreeSelect',
    group: BEAR_PALETTE_GROUP.FORM,
    html: wrap('TreeSelect', 'TreeSelect'),
  },
  {
    id: 'tree-view',
    label: 'TreeView',
    bearComponent: 'TreeView',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('TreeView', 'TreeView'),
  },
  {
    id: 'typewriter',
    label: 'Typewriter',
    bearComponent: 'Typewriter',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Typewriter', 'Typewriter'),
  },
  {
    id: 'typography',
    label: 'Typography',
    bearComponent: 'Typography',
    group: BEAR_PALETTE_GROUP.BASIC,
    html: wrap('Typography', '<h2>Heading</h2><p>Body text.</p>'),
  },
  {
    id: 'virtual-list',
    label: 'VirtualList',
    bearComponent: 'VirtualList',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('VirtualList', 'VirtualList'),
  },
  {
    id: 'watermark',
    label: 'Watermark',
    bearComponent: 'Watermark',
    group: BEAR_PALETTE_GROUP.GENERAL,
    html: wrap('Watermark', 'Watermark'),
  },
];

export const BEAR_PALETTE_GROUPS: readonly BearPaletteWidget['group'][] = [
  BEAR_PALETTE_GROUP.BASIC,
  BEAR_PALETTE_GROUP.LAYOUT,
  BEAR_PALETTE_GROUP.MEDIA,
  BEAR_PALETTE_GROUP.FORM,
  BEAR_PALETTE_GROUP.FEEDBACK,
  BEAR_PALETTE_GROUP.OVERLAY,
  BEAR_PALETTE_GROUP.GENERAL,
];
